### ISSUE TITLE
Back button not closing the app

### ISSUE THREAD

**Issue by mryogesh** [abhriyaroy/StockR#1]
https://user-images.githubusercontent.com/7595175/122245245-31015100-cee3-11eb-88b8-f0b68c7829ed.mp4

Attached video for reference.

**Comment by hiteshchopra11** [comment]
I have fixed the issue and raised a PR for the same.

https://github.com/abhriyaroy/StockR/pull/2

The issue is basically because on pressing the back button inside the Recommendation Fragment, the Recommendation Fragment is removed from the stack and the SplashFragment is on the top. Now as we are in the Splash Fragment, it redirects us back to RecommendationFragment after some short delay. So a vicious cycle is formed and hence this issue. I have fixed it by finishing the activity on Back Press inside the Recommendation Fragment, as technically the app should be closed on pressing the back Buttton here and there is no point to switch back to the Splash Fragment again.

CC-: @mryogesh @abhriyaroy
